// packages/pika-demo-react/src/pages/components/input/input.tsx
import React, { Component } from 'react';
import { View } from '@tarojs/components';
import { PkInput } from '@souche/pika-react';
import ShowCom from '../../../components/showCom';

export default class InputExample extends Component<any, any> {
    constructor() {
        // @ts-ignore
        super(...arguments);
        this.state = {
            value: '',
            value1: '',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
        };
    }

    handleChange (value) {
        this.setState({
            value: value,
            value1: value,
            value2: value,
            value3: value,
            value4: value,
            value5: value,
        });
        // 在小程序中，如果想改变 value 的值，需要 `return value` 从而改变输入框的当前值
        return value
    }
    handleClick () {
        console.log(123);
    }

    render() {
        return (
            <View className='inputExample'>
                <ShowCom title='基本使用'>
                    <PkInput name='value'
                             title='标准五个字'
                             type='text'
                             maxLength={5}
                             placeholder='请输入5个字'
                             value={this.state.value}
                             onChange={this.handleChange.bind(this)}/>
                </ShowCom>
                <ShowCom title='不同输入框类型'>
                    <PkInput
                        name='value1'
                        title='文本'
                        type='text'
                        placeholder='单行文本'
                        value={this.state.value1}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        name='value2'
                        title='数字'
                        type='number'
                        placeholder='请输入数字'
                        value={this.state.value2}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        name='value3'
                        title='密码'
                        type='password'
                        placeholder='密码不能少于10位数'
                        value={this.state.value3}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        name='value4'
                        title='身份证'
                        type='idcard'
                        placeholder='身份证号码'
                        value={this.state.value4}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        name='value5'
                        title='小数'
                        type='digit'
                        placeholder='请输入小数'
                        value={this.state.value5}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        name='value6'
                        border={false}
                        title='手机号码'
                        type='phone'
                        placeholder='手机号码'
                        value={this.state.value6}
                        onChange={this.handleChange.bind(this)}
                    />

                </ShowCom>
                <ShowCom title='不同状态'>
                    <PkInput
                        name='value6'
                        disabled
                        title='禁用'
                        type='text'
                        placeholder='禁止输入'
                        value={this.state.value1}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        error
                        title='出现错误'
                        type='text'
                        placeholder='点击按钮触发回调'
                        value={this.state.value2}
                        onChange={this.handleChange}
                        onErrorClick={this.handleClick.bind(this)}
                    />
                    <PkInput
                        editable={false}
                        title='不可编辑'
                        type='text'
                        placeholder='不可编辑'
                        value={this.state.value3}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        clear
                        border={false}
                        title='清除按钮'
                        placeholder='点击清除按钮清空内容'
                        type='text'
                        value={this.state.value4}
                        onChange={this.handleChange.bind(this)}
                    />
                    <PkInput
                        required
                        border={false}
                        title='必填项'
                        type='text' placeholder='必填项'
                        value={this.state.value5}
                        onChange={this.handleChange.bind(this)} />
                </ShowCom>
            </View>
        );
    }
}

// packages/pika-demo-vue/src/pages/components/form/input/index.vue
<template>
    <layout title="Input 输入框">
        <item title="基础使用">
            <pk-input title="标准六个文字" placeholder="标准六个文字" clear />
            <pk-input title="标准六个文字再长就换下行" />
            <pk-input placeholder="无标题" />
            <pk-input
                title="自动聚焦"
                :focus="true"
                placeholder="自动聚焦请在实机中查看"
            />
            <pk-input v-model="value1" :title="value1"></pk-input>
        </item>
        <item title="输入框类型">
            <pk-input title="文本" type="text" placeholder="单行文本" />
            <pk-input title="数字" type="number" placeholder="数字" />
            <pk-input title="密码" type="password" placeholder="密码" />
            <pk-input title="身份证" type="idcard" placeholder="身份证号码" />
            <pk-input title="小数" type="digit" placeholder="小数" />
            <pk-input title="手机号码" type="phone" placeholder="手机号码" />
        </item>
        <item title="输入框状态">
            <pk-input
                @click="disabledClick"
                disabled
                title="禁用"
                type="text"
                placeholder="禁用"
            />
            <pk-input
                title="错误"
                type="text"
                placeholder="错误"
                error
                @error-click="errorClick"
            />
            <pk-input
                title="清除"
                type="text"
                placeholder="清除输入"
                clear
                value="清理这里的内容"
            />
            <pk-input
                title="必填项"
                type="text"
                placeholder="必填项"
                required
            />
            <pk-input
                @keyboard-height-change="onKeyboardHeightChange"
                title="键盘高度"
                type="text"
                placeholder="监听键盘高度变化"
            />
        </item>
        <item title="自定义右侧">
            <pk-input title="文本" type="text" placeholder="单行文本">
                <view class="custom-text">输入验证码</view>
            </pk-input>
        </item>
    </layout>
</template>

<script>
import { PkInput } from '@souche/pika-vue';
import Layout from '@/components/layout/index';
import Item from '@/components/layout/item';

export default {
    name: 'PgInput',
    components: {
        PkInput,
        Layout,
        Item,
    },
    data() {
        return {
            value1: 'V-MODEL',
        };
    },
    methods: {
        onKeyboardHeightChange(val) {
            console.log(val);
        },
        errorClick() {
            console.log('error click !');
        },
        disabledClick() {
            console.log('input disabled');
        },
    },
};
</script>

<style lang="scss">
.custom-text {
    color: rgb(62, 130, 189);
}
</style>
