// packages/pika-demo-react/src/pages/components/form/form.tsx
import React, { Component } from 'react';
import { View } from '@tarojs/components';
import { PkForm, PkInput, PkButton } from '@souche/pika-react';
import ShowCom from '../../../components/showCom';

export default class FormExample extends Component<any, any> {
    constructor(props: any) {
        super(props);
        this.state = {
            username: '',
            password: '',
        };
    }
    onSubmit() {
        console.log(this.state.username, this.state.password);
    }
    onReset() {
        this.setState({
            username: '',
            password: '',
        });
    }
    render() {
        return (
            <View className='formExample'>
                <ShowCom title='基本使用'>
                    <PkForm
                        onSubmit={this.onSubmit.bind(this)}
                        onReset={this.onReset.bind(this)}
                        customStyle={''}
                    >
                        <PkInput
                            name='username'
                            title='用户名'
                            type='text'
                            value={this.state.username}
                            onChange={val => this.setState({ username: val })}
                        />
                        <PkInput
                            name='password'
                            title='密码'
                            type='password'
                            value={this.state.password}
                            onChange={val => this.setState({ password: val })}
                        />
                        <PkButton formType='submit'>提交</PkButton>
                        <PkButton formType='reset'>重置</PkButton>
                    </PkForm>
                </ShowCom>
            </View>
        );
    }
}

// packages/pika-demo-vue/src/pages/components/form/form/index.vue
<template>
    <view class="pg-form">
        <layout title="Form 表单">
            <item title="基础使用">
                <pk-form @submit="onSubmit" @reset="onReset">
                    <pk-input
                        title="用户名"
                        type="text"
                        v-model="username"
                    ></pk-input>
                    <pk-input
                        title="密码"
                        type="password"
                        v-model="password"
                    ></pk-input>
                    <view class="ctrl-group">
                        <pk-button form-type="submit">提交</pk-button>
                        <pk-button form-type="reset">重置</pk-button>
                    </view>
                </pk-form>
            </item>
        </layout>
    </view>
</template>

<script>
import { PkForm, PkInput, PkButton } from '@souche/pika-vue';
import Layout from '@/components/layout/index';
import Item from '@/components/layout/item';

export default {
    name: 'PgForm',
    components: {
        PkForm,
        PkInput,
        PkButton,
        Layout,
        Item,
    },
    data() {
        return {
            username: '',
            password: '',
        };
    },
    methods: {
        onSubmit() {
            console.log(this.username, this.password);
        },
        onReset() {
            this.username = '';
            this.password = '';
        },
    },
};
</script>

<style lang="scss">
.pg-form {
    .ctrl-group {
        text-align: center;
        margin-top: 20px;
    }
}
</style>
